This is a small enhancement of the original library to work with the TTGO RS v 1.2
I found a lot of examles that are using a so called MySD library, but could not determine the source of it. 

So I forked the original lib and merged the differences.

Thanks to the unknow programmer and thanks to William Greiman, for this lib.

If you want, visit also http://www.fambach.net for more infomations

= SD Library for Arduino =

image:https://travis-ci.org/arduino-libraries/SD.svg?branch=master[Build Status, link=https://travis-ci.org/arduino-libraries/SD]

The SD library allows for reading from and writing to SD cards.

For more information about this library please visit us at
http://www.arduino.cc/en/Reference/SD

== License ==

 Copyright (C) 2009 by William Greiman
Copyright (c) 2010 SparkFun Electronics

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
